language: cpp
compiler:
  - clang
  - gcc

before_install:
  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-add-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise     main"; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-add-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main"; fi
  - if [ "$CXX" == "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -; fi

  - sudo apt-get update -q
  - apt-cache search clang
  - apt-cache madison clang-3.5

install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

  # clang 3.5
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated clang-3.5; fi
  - if [ "$CXX" == "clang++" ]; then which clang++; ls -l /usr/bin/clang*; ls -ld /usr/local/clang*; fi
  - if [ "$CXX" == "clang++" ]; then CXX=/usr/bin/clang++-3.5; fi

script: 
  - $CXX --version
  - make testex
